### ISSUE TITLE
Current package fails to build

### ISSUE THREAD

**Issue by hfiguiere** [flathub/org.wesnoth.Wesnoth#11]
The current package fails to build because of appdata validation.

It's missing the `oars` tag and `releases`.

This blocks issue #10.

**Comment by loonycyborg** [comment]
I figured out how to add oars entry, but I have no idea how best to maintain <releases> tag. Need to somehow autogenerate it from git tags I guess? If I just fill it manually it's nearly guaranteed that it'll become outdated sooner or later. Probably sooner. I'd prefer if <releases> requirement didn't exist. Is it actually used somewhere for something?

**Comment by hfiguiere** [comment]
I do it manually by summarizing the release note.

**Comment by loonycyborg** [comment]
Honestly, previously I just did a version bump in JSON file and then a commit. I'm kinda unwilling to give up this simple workflow. I don't want to have to edit the xml file for each release. Unless release managers are willing to update appdata file themselves I would have to add new ```<release>``` tag in a patch against appdata file that is already provided upstream. Either that or fill it with bogus data that pass validation. Although I have commit access to upstream repo, another person does the tagging and I start packaging work already after that.

**Comment by hfiguiere** [comment]
You could upstream this so that upstream can be convinced to help more easily. It doesn't need a lot of information.

**Comment by loonycyborg** [comment]
Well it's totally fine to fill it in once but ```<release>``` field needs adding for each release with only two mandatory fields: version and date which don't require manual input to figure out, so it's most definitely something that should be automated.

**Comment by hfiguiere** [comment]
Still fails. you forgot OARS in the flatpak

**Comment by loonycyborg** [comment]
Added it now
