### ISSUE TITLE
Translations do not work

### ISSUE THREAD

**Issue by wlinna** [flathub/org.wesnoth.Wesnoth#2]
I'm using Solus (this is a pretty new distro for me), and I noticed, that translations do not work. I tried at least Russian and Finnish.

They appear in the menu, but selecting the language and pressing Ok doesn't change the language.

Only UMC campaigns seem to be translated

**Comment by loonycyborg** [comment]
Seems it works fine after update to 1.14

**Comment by wlinna** [comment]
What do you mean? There doesn't seem to be 1.14 yet. I wouldn't suggest upgrading to 1.13.x yet, as they are development versions, and many / some add-ons aren't available for it, yet.

(In fact, the only reason I installed Wesnoth using flatpak was because Solus distro for some reason packages a development version of Wesnoth)

**Comment by loonycyborg** [comment]
Works for me with 1.14.x . Tested on Gentoo and Fedora. If it still doesn't for you, reopen and provide more data.
