### ISSUE TITLE
no license in the appdata file

### ISSUE THREAD

**Issue by andreasn** [flathub/org.wesnoth.Wesnoth#3]
It seems the appdata file that is shipped in the flatpak build lacks a license field, making the license show as "unknown" in GNOME Software.
It seems the upstream appdata file has this info. https://github.com/wesnoth/wesnoth/blob/3777a5b307992e3e45240c9ddcd93c02d1097cc3/packaging/wesnoth.appdata.xml

**Comment by andreasn** [comment]
But maybe that will be fixed by itself once a new stable version is available?

**Comment by TingPing** [comment]
It is probably reasonable to backport the upstream file.

**Comment by andreasn** [comment]
Seems the new stable is on it's way, so best to wait for that, and not bother with weird deltas. Closing.
